# Generated by Django 4.2.4 on 2023-08-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0028_personal_info_background_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hardskill",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="softskill",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
